# Generated by Django 5.1.4 on 2024-12-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_atribute_autopart_image_autopartcharacteristic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopart',
            name='images',
        ),
        migrations.CreateModel(
            name='AutoPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.autopart', verbose_name='Автозапчасть')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение автозапчасти',
                'verbose_name_plural': 'Изображения автозапчастей',
            },
        ),
    ]
