# Generated by Django 5.1.4 on 2024-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_autopart_images_autopartimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopartimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterModelOptions(
            name='autopartcharacteristic',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='autopartimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
