# Generated by Django 5.1.4 on 2024-12-05 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
            },
        ),
        migrations.AlterField(
            model_name="autopart",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="autopart",
            name="mark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="database.automark",
                verbose_name="Марка",
            ),
            preserve_default=False,
        ),
    ]
