# Generated by Django 5.1.4 on 2024-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_automark_alter_autopart_description_autopart_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automark',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
