# Generated by Django 5.1.4 on 2024-12-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="images/", verbose_name="Изображение"),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "obj_type",
                    models.CharField(
                        choices=[("delivery", "Доставка"), ("payment", "Платеж")],
                        max_length=256,
                        verbose_name="Тип объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип",
                "verbose_name_plural": "Типы",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="company",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачен"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Общая стоимость",
            ),
        ),
        migrations.AddField(
            model_name="autopart",
            name="image",
            field=models.ManyToManyField(
                to="database.image", verbose_name="Изображения"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_type",
                to="database.types",
                verbose_name="Тип доставки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_type",
                to="database.types",
                verbose_name="Тип оплаты",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AutoPartImage",
        ),
    ]
