# Generated by Django 5.1.4 on 2024-12-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_image_types_remove_customuser_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopart',
            name='image',
        ),
        migrations.CreateModel(
            name='AutoPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('auto_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.autopart', verbose_name='Автозапчасть')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
