# Generated by Django 5.1.4 on 2024-12-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_autopart_image_autopartimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='database.order', verbose_name='Заказ'),
        ),
    ]
