# Generated by Django 5.1.4 on 2024-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
